#!/bin/bash
set -e
# ═══════════════════════════════════════════════════════════════
# EdgeCitadel: Join as an agent (run on the agent's machine)
#
# Usage: ./join.sh <server-host> <mqtt-password> [agent-id]
#
# Auto-detects: display name, role, device type, gateway URL,
# gateway token. Agent ID defaults to hostname if not provided.
# ═══════════════════════════════════════════════════════════════

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ ok ]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()   { echo -e "${RED}[fail]${NC} $*"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Parse args ──
CITADEL_HOST="${1:-}"
MQTT_PASS="${2:-}"
AGENT_ID_ARG="${3:-}"

if [[ -z "$CITADEL_HOST" || -z "$MQTT_PASS" ]]; then
    echo "Usage: ./join.sh <server-host> <mqtt-password> [agent-id]"
    echo ""
    echo "  server-host   IP or hostname of the EdgeCitadel server"
    echo "  mqtt-password Password generated by add-agent.sh on the server"
    echo "  agent-id      Agent ID (default: auto-detect from hostname)"
    echo ""
    echo "Example: ./join.sh 100.97.29.74 xK9mPv2Ld8nQwR3s us-claw-remote"
    exit 1
fi

# ═══════════════════════════════════════════════════════════════
# Auto-detect agent identity
# ═══════════════════════════════════════════════════════════════

# Agent ID: use argument if provided, otherwise hostname, lowercased, sanitized
if [[ -n "$AGENT_ID_ARG" ]]; then
    AGENT_ID=$(echo "$AGENT_ID_ARG" | tr '[:upper:]' '[:lower:]' | tr ' _.' '-')
else
    AGENT_ID=$(hostname -s 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr ' _.' '-')
    if [[ -z "$AGENT_ID" || "$AGENT_ID" == "localhost" ]]; then
        AGENT_ID="agent-$(cat /etc/machine-id 2>/dev/null | head -c 8 || echo $$)"
    fi
fi

# Display name: title-cased hostname
AGENT_DISPLAY=$(echo "$AGENT_ID" | sed 's/-/ /g' | sed 's/\b\w/\u&/g')

# MQTT user = agent ID
MQTT_USER="$AGENT_ID"

# Device type: auto-detect
detect_device_type() {
    if [[ -f /proc/device-tree/model ]] && grep -qi "raspberry" /proc/device-tree/model 2>/dev/null; then
        echo "raspberry_pi"
    elif [[ -d /sys/class/power_supply/BAT0 ]]; then
        echo "laptop"
    elif grep -qi "android" /proc/version 2>/dev/null; then
        echo "smartphone"
    elif [[ -f /sys/hypervisor/type ]] || grep -qi "amazon\|google\|azure\|virtualbox\|vmware\|kvm" /sys/class/dmi/id/product_name 2>/dev/null; then
        echo "cloud_vm"
    else
        echo "server"
    fi
}
AGENT_DEVICE_TYPE=$(detect_device_type)

# ═══════════════════════════════════════════════════════════════
# Auto-detect OpenClaw gateway
# ═══════════════════════════════════════════════════════════════

GATEWAY_URL=""
GATEWAY_TOKEN=""
WAKE_MODE="api"

# Check common gateway ports
for port in 18789 8789 3000; do
    if curl -sf --max-time 2 "http://127.0.0.1:${port}/v1/models" &>/dev/null || \
       curl -sf --max-time 2 "http://127.0.0.1:${port}/health" &>/dev/null; then
        GATEWAY_URL="http://127.0.0.1:${port}"
        break
    fi
done

# Try to find gateway token from openclaw config
find_gateway_token() {
    # Check common openclaw config locations
    for cfg in \
        "$HOME/.openclaw/gateway.env" \
        "$HOME/.openclaw/config.json" \
        "$HOME/.openclaw/.env" \
        "$HOME/.openclaw/workspace/.env" \
        "/etc/openclaw/gateway.env"; do
        if [[ -f "$cfg" ]]; then
            # Look for token patterns
            local token
            token=$(grep -oP '(?:GATEWAY_TOKEN|HOOKS_TOKEN|API_KEY|AUTH_TOKEN|BEARER_TOKEN)\s*[=:]\s*["\x27]?\K[^"\x27\s]+' "$cfg" 2>/dev/null | head -1)
            if [[ -n "$token" ]]; then
                echo "$token"
                return
            fi
        fi
    done
    # Check systemd service environment
    for svc in openclaw-gateway openclaw openclaw-agent; do
        local envfile
        envfile=$(systemctl --user show "$svc" 2>/dev/null | grep -oP 'EnvironmentFile=\K.*' | head -1)
        if [[ -n "$envfile" && -f "$envfile" ]]; then
            local token
            token=$(grep -oP '(?:GATEWAY_TOKEN|HOOKS_TOKEN)\s*=\s*["\x27]?\K[^"\x27\s]+' "$envfile" 2>/dev/null | head -1)
            if [[ -n "$token" ]]; then
                echo "$token"
                return
            fi
        fi
    done
}
GATEWAY_TOKEN=$(find_gateway_token)

# Also detect role from openclaw config if available
AGENT_ROLE="Agent"
if [[ -f "$HOME/.openclaw/config.json" ]]; then
    local_role=$(python3 -c "import json; c=json.load(open('$HOME/.openclaw/config.json')); print(c.get('role', c.get('agent_role', '')))" 2>/dev/null || true)
    [[ -n "$local_role" ]] && AGENT_ROLE="$local_role"
fi

# ═══════════════════════════════════════════════════════════════
# Show config
# ═══════════════════════════════════════════════════════════════

echo ""
echo "═══════════════════════════════════════════════════════════"
echo -e " ${CYAN}EdgeCitadel Agent Setup${NC}"
echo "═══════════════════════════════════════════════════════════"
echo ""
info "Agent ID:     $AGENT_ID"
info "Display name: $AGENT_DISPLAY"
info "Device type:  $AGENT_DEVICE_TYPE"
info "Server:       $CITADEL_HOST:1883"
if [[ -n "$GATEWAY_URL" ]]; then
    info "Gateway:      $GATEWAY_URL"
    [[ -n "$GATEWAY_TOKEN" ]] && info "Gateway auth: (found)" || warn "Gateway auth: (not found — agent won't process commands)"
else
    warn "Gateway:      not detected (agent will appear on dashboard but can't process commands)"
fi
echo ""

# ═══════════════════════════════════════════════════════════════
# Check prerequisites
# ═══════════════════════════════════════════════════════════════

info "Checking prerequisites..."

if ! command -v node &>/dev/null; then
    err "Node.js not found. Install Node.js >= 16 first."
    exit 1
fi
ok "Node.js $(node -v)"

# Install mqtt module if needed
cd "$SCRIPT_DIR/openclaw-client"
if ! node -e "require('mqtt')" 2>/dev/null; then
    info "Installing mqtt module..."
    [[ -f package.json ]] || npm init -y &>/dev/null
    npm install --silent mqtt 2>/dev/null
fi
ok "mqtt module ready"

# ═══════════════════════════════════════════════════════════════
# Test MQTT connection
# ═══════════════════════════════════════════════════════════════

info "Testing MQTT connection..."

MQTT_TEST=$(node -e "
const mqtt = require('mqtt');
const c = mqtt.connect('mqtt://${CITADEL_HOST}:1883', {
    username: '${MQTT_USER}', password: '${MQTT_PASS}',
    clientId: 'test-' + Date.now(), connectTimeout: 10000
});
const t = setTimeout(() => { console.log('TIMEOUT'); process.exit(1); }, 12000);
c.on('connect', () => { clearTimeout(t); console.log('OK'); c.end(); });
c.on('error', (e) => { clearTimeout(t); console.log('ERROR:' + e.message); c.end(); process.exit(1); });
" 2>&1)

if [[ "$MQTT_TEST" == "OK" ]]; then
    ok "MQTT connected"
else
    err "MQTT connection failed: $MQTT_TEST"
    echo ""
    echo "  Check that:"
    echo "    1. EdgeCitadel is running on $CITADEL_HOST"
    echo "    2. Port 1883 is reachable (firewall / Tailscale)"
    echo "    3. add-agent.sh was run on the server for this agent"
    exit 1
fi

# ═══════════════════════════════════════════════════════════════
# Write config file
# ═══════════════════════════════════════════════════════════════

CONFIG_FILE="$SCRIPT_DIR/openclaw-client/agent.env"
cat > "$CONFIG_FILE" <<EOF
AGENT_ID=${AGENT_ID}
AGENT_DISPLAY=${AGENT_DISPLAY}
AGENT_ROLE=${AGENT_ROLE}
AGENT_DEVICE_TYPE=${AGENT_DEVICE_TYPE}
CITADEL_HOST=${CITADEL_HOST}
CITADEL_PORT=1883
MQTT_USER=${MQTT_USER}
MQTT_PASS=${MQTT_PASS}
GATEWAY_URL=${GATEWAY_URL}
WAKE_MODE=${WAKE_MODE}
GATEWAY_TOKEN=${GATEWAY_TOKEN}
HEARTBEAT_SEC=30
EOF
chmod 600 "$CONFIG_FILE"

# ═══════════════════════════════════════════════════════════════
# Generate the listener script
# ═══════════════════════════════════════════════════════════════

LISTENER_SCRIPT="$SCRIPT_DIR/openclaw-client/mqtt-listener.js"

cat > "$LISTENER_SCRIPT" <<'JSEOF'
#!/usr/bin/env node
const mqtt = require('mqtt');
const http = require('http');
const https = require('https');
const os = require('os');

const ID      = process.env.AGENT_ID;
if (!ID) { console.error('AGENT_ID required'); process.exit(1); }

const DISPLAY = process.env.AGENT_DISPLAY   || ID.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const ROLE    = process.env.AGENT_ROLE       || 'Agent';
const DEVICE  = process.env.AGENT_DEVICE_TYPE|| 'server';
const HOST    = process.env.CITADEL_HOST     || process.env.MQTT_HOST || '127.0.0.1';
const PORT    = parseInt(process.env.CITADEL_PORT || process.env.MQTT_PORT || '1883');
const USER    = process.env.MQTT_USER        || ID;
const PASS    = process.env.MQTT_PASS        || '';
const GW_URL  = process.env.GATEWAY_URL      || '';
const GW_TOK  = process.env.GATEWAY_TOKEN    || process.env.HOOKS_TOKEN || '';
const WAKE    = process.env.WAKE_MODE        || 'api';
const HB_SEC  = parseInt(process.env.HEARTBEAT_SEC || '30');
const T       = `[${ID}]`;

function getIP() {
    for (const ifs of Object.values(os.networkInterfaces()))
        for (const i of ifs) if (i.family==='IPv4' && !i.internal) return i.address;
    return '127.0.0.1';
}

const client = mqtt.connect(`mqtt://${HOST}:${PORT}`, {
    username: USER, password: PASS,
    clientId: `${ID}-${Date.now()}`,
    reconnectPeriod: 5000,
    will: { topic: `agents/status/${ID}`,
            payload: JSON.stringify({status:'offline',timestamp:new Date().toISOString()}),
            qos:1, retain:true }
});

let hbTimer = null;

function heartbeat() {
    const la = os.loadavg()[0], cpus = os.cpus().length||1;
    const tm = os.totalmem(), fm = os.freemem();
    client.publish(`agents/heartbeat/${ID}`, JSON.stringify({
        agent_id:ID, display_name:DISPLAY, role:ROLE, device_type:DEVICE,
        status:'online',
        cpu_percent: Math.round((la/cpus)*1000)/10,
        memory_percent: Math.round(((tm-fm)/tm)*1000)/10,
        ip_address: getIP(),
        capabilities: ['chat','task_execution','mqtt_listener'],
        timestamp: new Date().toISOString()
    }), {qos:1});
}

client.on('connect', () => {
    console.log(T, `Connected to ${HOST}:${PORT}`);
    client.subscribe(`agents/inbox/${ID}`, {qos:1});
    client.subscribe('agents/broadcast', {qos:1});
    // Register
    client.publish(`agents/register/${ID}`, JSON.stringify({
        agent_id:ID, display_name:DISPLAY, role:ROLE, device_type:DEVICE,
        capabilities:['chat','task_execution','mqtt_listener'],
        ip_address:getIP(), status:'online', timestamp:new Date().toISOString()
    }), {qos:1});
    heartbeat();
    if (hbTimer) clearInterval(hbTimer);
    hbTimer = setInterval(heartbeat, HB_SEC*1000);
    console.log(T, 'Online. Listening for commands.');
});

client.on('message', (topic, message) => {
    try {
        const m = JSON.parse(message.toString());
        const from = m.from||m.sender_id||'unknown';
        const content = m.content||m.message||'';
        const corrId = m.correlationId||m.correlation_id||'';
        if (from===ID || !content.trim()) return;
        console.log(T, `${from}: ${content.substring(0,120)}`);
        if (!GW_URL) { console.log(T, 'No gateway configured, skipping'); return; }
        callGateway(from, content, corrId);
    } catch(e) { console.error(T, 'Parse:', e.message); }
});

function callGateway(from, content, corrId) {
    const body = WAKE==='webhook'
        ? JSON.stringify({text:`[MQTT] ${from}: ${content.substring(0,500)}`, mode:'now'})
        : JSON.stringify({messages:[{role:'user',content:`[MQTT from ${from}] ${content}`}],stream:false});
    const path = WAKE==='webhook' ? '/hooks/wake' : '/v1/chat/completions';
    const url = new URL(GW_URL + path);
    const isS = url.protocol==='https:';
    const hdr = {'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)};
    if (GW_TOK) hdr['Authorization'] = `Bearer ${GW_TOK}`;
    const req = (isS?https:http).request({
        hostname:url.hostname, port:url.port||(isS?443:80),
        path:url.pathname, method:'POST', headers:hdr, timeout:600000
    }, res => {
        let d=''; res.on('data',c=>d+=c);
        res.on('end', () => {
            console.log(T, `Gateway ${res.statusCode}`);
            if (WAKE==='webhook') return; // webhook agents reply themselves
            try {
                const r = JSON.parse(d);
                const txt = r.choices?.[0]?.message?.content;
                if (txt?.trim()) reply(from, txt, corrId);
            } catch(e){}
        });
    });
    req.on('error', e=>console.error(T,'Gateway error:',e.message));
    req.on('timeout', ()=>{req.destroy();console.error(T,'Gateway timeout')});
    req.write(body); req.end();
}

function reply(to, content, corrId) {
    const msg = {
        from:ID, to, sender_id:ID, receiver_id:to,
        type:'response', message_type:'result',
        content, message:content,
        correlationId:corrId||'', correlation_id:corrId||'',
        timestamp:new Date().toISOString()
    };
    client.publish(`agents/inbox/${to}`, JSON.stringify(msg), {qos:1});
    client.publish('agents/mirror', JSON.stringify(msg), {qos:1});
    console.log(T, `-> ${to}: ${content.substring(0,80)}`);
}

client.on('error', e=>console.error(T,'MQTT:',e.message));
client.on('offline', ()=>{ if(hbTimer){clearInterval(hbTimer);hbTimer=null;} console.log(T,'Offline, reconnecting...'); });

function shutdown() {
    if(hbTimer) clearInterval(hbTimer);
    client.publish(`agents/status/${ID}`,JSON.stringify({status:'offline',timestamp:new Date().toISOString()}),
        {qos:1,retain:true}, ()=>{client.end();process.exit(0);});
    setTimeout(()=>process.exit(0),2000);
}
process.on('SIGINT',shutdown); process.on('SIGTERM',shutdown);
console.log(T, `Listener starting | ${DISPLAY} (${ROLE}) | ${HOST}:${PORT} | GW: ${GW_URL||'none'}`);
JSEOF

chmod +x "$LISTENER_SCRIPT"
ok "Listener installed"

# ═══════════════════════════════════════════════════════════════
# Install systemd service
# ═══════════════════════════════════════════════════════════════

info "Setting up systemd service..."

SERVICE_DIR="$HOME/.config/systemd/user"
SERVICE_NAME="edgecitadel-${AGENT_ID}.service"
mkdir -p "$SERVICE_DIR"

cat > "$SERVICE_DIR/$SERVICE_NAME" <<EOF
[Unit]
Description=EdgeCitadel agent ${AGENT_ID}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$(which node) ${LISTENER_SCRIPT}
Restart=always
RestartSec=5
EnvironmentFile=${CONFIG_FILE}

[Install]
WantedBy=default.target
EOF

# Stop ALL old edgecitadel services (handles renamed agent IDs)
for old_svc in $(systemctl --user list-units --no-legend 'edgecitadel-*' 2>/dev/null | awk '{print $1}'); do
    systemctl --user stop "$old_svc" 2>/dev/null || true
    systemctl --user disable "$old_svc" 2>/dev/null || true
done
systemctl --user daemon-reload
systemctl --user enable "$SERVICE_NAME" 2>/dev/null
systemctl --user start "$SERVICE_NAME"

sleep 3
if systemctl --user is-active --quiet "$SERVICE_NAME"; then
    ok "Service running"
else
    err "Service failed. Check: journalctl --user -u $SERVICE_NAME -n 20"
    exit 1
fi

# ═══════════════════════════════════════════════════════════════
# Done
# ═══════════════════════════════════════════════════════════════

echo ""
echo "═══════════════════════════════════════════════════════════"
echo -e " ${GREEN}${AGENT_DISPLAY} joined EdgeCitadel!${NC}"
echo ""
echo "  Dashboard: http://${CITADEL_HOST}"
echo "  Logs:      journalctl --user -u $SERVICE_NAME -f"
echo "  Restart:   systemctl --user restart $SERVICE_NAME"
echo "  Stop:      systemctl --user stop $SERVICE_NAME"
echo "═══════════════════════════════════════════════════════════"
