#!/bin/bash
set -e
# ═══════════════════════════════════════════════════════════════
# EdgeCitadel: Join as an agent (run on the agent's machine)
#
# Usage: ./join.sh <server-host> <mqtt-password> [agent-id]
#
# Auto-detects: display name, role, device type.
# Agent ID defaults to hostname if not provided.
# Requires: Node.js, openclaw CLI (with model auth configured).
# ═══════════════════════════════════════════════════════════════

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ ok ]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()   { echo -e "${RED}[fail]${NC} $*"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Parse args ──
CITADEL_HOST="${1:-}"
MQTT_PASS="${2:-}"
AGENT_ID_ARG="${3:-}"

if [[ -z "$CITADEL_HOST" || -z "$MQTT_PASS" ]]; then
    echo "Usage: ./join.sh <server-host> <mqtt-password> [agent-id]"
    echo ""
    echo "  server-host   IP or hostname of the EdgeCitadel server"
    echo "  mqtt-password Password generated by add-agent.sh on the server"
    echo "  agent-id      Agent ID (default: auto-detect from hostname)"
    echo ""
    echo "Example: ./join.sh 100.97.29.74 xK9mPv2Ld8nQwR3s us-claw-remote"
    exit 1
fi

# ═══════════════════════════════════════════════════════════════
# Auto-detect agent identity
# ═══════════════════════════════════════════════════════════════

# Agent ID: use argument if provided, otherwise hostname, lowercased, sanitized
if [[ -n "$AGENT_ID_ARG" ]]; then
    AGENT_ID=$(echo "$AGENT_ID_ARG" | tr '[:upper:]' '[:lower:]' | tr ' _.' '-')
else
    AGENT_ID=$(hostname -s 2>/dev/null | tr '[:upper:]' '[:lower:]' | tr ' _.' '-')
    if [[ -z "$AGENT_ID" || "$AGENT_ID" == "localhost" ]]; then
        AGENT_ID="agent-$(cat /etc/machine-id 2>/dev/null | head -c 8 || echo $$)"
    fi
fi

# Display name: title-cased hostname
AGENT_DISPLAY=$(echo "$AGENT_ID" | sed 's/-/ /g' | sed 's/\b\w/\u&/g')

# MQTT user = agent ID
MQTT_USER="$AGENT_ID"

# Device type: auto-detect
detect_device_type() {
    if [[ -f /proc/device-tree/model ]] && grep -qi "raspberry" /proc/device-tree/model 2>/dev/null; then
        echo "raspberry_pi"
    elif [[ -d /sys/class/power_supply/BAT0 ]]; then
        echo "laptop"
    elif grep -qi "android" /proc/version 2>/dev/null; then
        echo "smartphone"
    elif [[ -f /sys/hypervisor/type ]] || grep -qi "amazon\|google\|azure\|virtualbox\|vmware\|kvm" /sys/class/dmi/id/product_name 2>/dev/null; then
        echo "cloud_vm"
    else
        echo "server"
    fi
}
AGENT_DEVICE_TYPE=$(detect_device_type)

# Also detect role from openclaw config if available
AGENT_ROLE="Agent"
if [[ -f "$HOME/.openclaw/config.json" ]]; then
    local_role=$(python3 -c "import json; c=json.load(open('$HOME/.openclaw/config.json')); print(c.get('role', c.get('agent_role', '')))" 2>/dev/null || true)
    [[ -n "$local_role" ]] && AGENT_ROLE="$local_role"
fi

# ═══════════════════════════════════════════════════════════════
# Show config
# ═══════════════════════════════════════════════════════════════

echo ""
echo "═══════════════════════════════════════════════════════════"
echo -e " ${CYAN}EdgeCitadel Agent Setup${NC}"
echo "═══════════════════════════════════════════════════════════"
echo ""
info "Agent ID:     $AGENT_ID"
info "Display name: $AGENT_DISPLAY"
info "Device type:  $AGENT_DEVICE_TYPE"
info "Server:       $CITADEL_HOST:1883"
echo ""

# ═══════════════════════════════════════════════════════════════
# Check prerequisites
# ═══════════════════════════════════════════════════════════════

info "Checking prerequisites..."

if ! command -v node &>/dev/null; then
    err "Node.js not found. Install Node.js >= 16 first."
    exit 1
fi
ok "Node.js $(node -v)"

if ! command -v openclaw &>/dev/null; then
    err "openclaw CLI not found. Install it first: npm i -g openclaw"
    exit 1
fi
ok "openclaw $(openclaw -V 2>/dev/null || echo '(installed)')"

# Verify openclaw has model auth configured
if ! openclaw models status --status-json 2>/dev/null | node -e "
    let d=''; process.stdin.on('data',c=>d+=c); process.stdin.on('end',()=>{
        try { const j=JSON.parse(d); process.exit(j.configured ? 0 : 1); }
        catch(e) { process.exit(1); }
    });" 2>/dev/null; then
    warn "openclaw model auth may not be configured. Run: openclaw models auth paste-token --provider anthropic"
fi

# Install mqtt module if needed
cd "$SCRIPT_DIR/openclaw-client"
if ! node -e "require('mqtt')" 2>/dev/null; then
    info "Installing mqtt module..."
    [[ -f package.json ]] || npm init -y &>/dev/null
    npm install --silent mqtt 2>/dev/null
fi
ok "mqtt module ready"

# ═══════════════════════════════════════════════════════════════
# Test MQTT connection
# ═══════════════════════════════════════════════════════════════

info "Testing MQTT connection..."

MQTT_TEST=$(node -e "
const mqtt = require('mqtt');
const c = mqtt.connect('mqtt://${CITADEL_HOST}:1883', {
    username: '${MQTT_USER}', password: '${MQTT_PASS}',
    clientId: 'test-' + Date.now(), connectTimeout: 10000
});
const t = setTimeout(() => { console.log('TIMEOUT'); process.exit(1); }, 12000);
c.on('connect', () => { clearTimeout(t); console.log('OK'); c.end(); });
c.on('error', (e) => { clearTimeout(t); console.log('ERROR:' + e.message); c.end(); process.exit(1); });
" 2>&1)

if [[ "$MQTT_TEST" == "OK" ]]; then
    ok "MQTT connected"
else
    err "MQTT connection failed: $MQTT_TEST"
    echo ""
    echo "  Check that:"
    echo "    1. EdgeCitadel is running on $CITADEL_HOST"
    echo "    2. Port 1883 is reachable (firewall / Tailscale)"
    echo "    3. add-agent.sh was run on the server for this agent"
    exit 1
fi

# ═══════════════════════════════════════════════════════════════
# Write config file
# ═══════════════════════════════════════════════════════════════

CONFIG_FILE="$SCRIPT_DIR/openclaw-client/agent.env"
OPENCLAW_BIN=$(which openclaw 2>/dev/null || echo "openclaw")
cat > "$CONFIG_FILE" <<EOF
AGENT_ID=${AGENT_ID}
AGENT_DISPLAY=${AGENT_DISPLAY}
AGENT_ROLE=${AGENT_ROLE}
AGENT_DEVICE_TYPE=${AGENT_DEVICE_TYPE}
CITADEL_HOST=${CITADEL_HOST}
CITADEL_PORT=1883
MQTT_USER=${MQTT_USER}
MQTT_PASS=${MQTT_PASS}
OPENCLAW_BIN=${OPENCLAW_BIN}
AGENT_TIMEOUT=600
HEARTBEAT_SEC=30
EOF
chmod 600 "$CONFIG_FILE"

# ═══════════════════════════════════════════════════════════════
# Verify listener script exists (shipped in repo, not generated)
# ═══════════════════════════════════════════════════════════════

LISTENER_SCRIPT="$SCRIPT_DIR/openclaw-client/mqtt-listener.js"

if [[ ! -f "$LISTENER_SCRIPT" ]]; then
    err "mqtt-listener.js not found at $LISTENER_SCRIPT"
    exit 1
fi
chmod +x "$LISTENER_SCRIPT"
ok "Listener ready"

# ═══════════════════════════════════════════════════════════════
# Install systemd service
# ═══════════════════════════════════════════════════════════════

info "Setting up systemd service..."

SERVICE_DIR="$HOME/.config/systemd/user"
SERVICE_NAME="edgecitadel-${AGENT_ID}.service"
mkdir -p "$SERVICE_DIR"

cat > "$SERVICE_DIR/$SERVICE_NAME" <<EOF
[Unit]
Description=EdgeCitadel agent ${AGENT_ID}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$(which node) ${LISTENER_SCRIPT}
Restart=always
RestartSec=5
EnvironmentFile=${CONFIG_FILE}

[Install]
WantedBy=default.target
EOF

# Stop ALL old edgecitadel services (handles renamed agent IDs)
for old_svc in $(systemctl --user list-units --no-legend 'edgecitadel-*' 2>/dev/null | awk '{print $1}'); do
    systemctl --user stop "$old_svc" 2>/dev/null || true
    systemctl --user disable "$old_svc" 2>/dev/null || true
done
systemctl --user daemon-reload
systemctl --user enable "$SERVICE_NAME" 2>/dev/null
systemctl --user start "$SERVICE_NAME"

sleep 3
if systemctl --user is-active --quiet "$SERVICE_NAME"; then
    ok "Service running"
else
    err "Service failed. Check: journalctl --user -u $SERVICE_NAME -n 20"
    exit 1
fi

# ═══════════════════════════════════════════════════════════════
# Done
# ═══════════════════════════════════════════════════════════════

echo ""
echo "═══════════════════════════════════════════════════════════"
echo -e " ${GREEN}${AGENT_DISPLAY} joined EdgeCitadel!${NC}"
echo ""
echo "  Dashboard: http://${CITADEL_HOST}"
echo "  Logs:      journalctl --user -u $SERVICE_NAME -f"
echo "  Restart:   systemctl --user restart $SERVICE_NAME"
echo "  Stop:      systemctl --user stop $SERVICE_NAME"
echo "═══════════════════════════════════════════════════════════"
