#!/bin/bash
set -e

# ═══════════════════════════════════════════════════════════════════
# EdgeCitadel Agent Join Script
#
# Run this on any machine with an OpenClaw agent to connect it to
# an EdgeCitadel dashboard. It will:
#   1. Create an MQTT user on the EdgeCitadel broker (via SSH)
#   2. Install the MQTT listener service (persistent connection)
#   3. Register as a systemd user service that auto-starts
#
# Prerequisites on THIS machine:
#   - Node.js >= 16
#   - npm install mqtt  (or: npm install -g mqtt)
#   - OpenClaw gateway running locally (default: http://127.0.0.1:18789)
#   - SSH access to the EdgeCitadel server OR pre-created MQTT credentials
#
# Usage:
#   ./join.sh                     # interactive setup
#   ./join.sh --config agent.env  # use existing config file
# ═══════════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${1:-$SCRIPT_DIR/agent.env}"
LISTENER_SCRIPT="$SCRIPT_DIR/mqtt-listener.js"

# ── Colors ──
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()   { echo -e "${RED}[error]${NC} $*"; }

# ═══════════════════════════════════════════════════════════════════
# Step 1: Gather configuration
# ═══════════════════════════════════════════════════════════════════

if [[ -f "$CONFIG_FILE" ]]; then
    info "Loading config from $CONFIG_FILE"
    source "$CONFIG_FILE"
else
    info "No config file found. Starting interactive setup."
    echo ""

    # Agent identity
    read -rp "Agent ID (lowercase, no spaces, e.g. us-claw-remote): " AGENT_ID
    read -rp "Display name (e.g. US Claw Remote): " AGENT_DISPLAY
    read -rp "Role (e.g. Assistant, IoT Controller, Mobile Agent): " AGENT_ROLE
    read -rp "Device type (e.g. server, raspberry_pi, smartphone): " AGENT_DEVICE_TYPE

    echo ""
    # EdgeCitadel server
    read -rp "EdgeCitadel MQTT host (IP or hostname, e.g. 100.97.29.74): " CITADEL_HOST
    read -rp "EdgeCitadel MQTT port [1883]: " CITADEL_PORT
    CITADEL_PORT="${CITADEL_PORT:-1883}"

    echo ""
    # MQTT credentials
    echo "MQTT credentials for this agent on the EdgeCitadel broker."
    echo "If you don't have them yet, the script can create them via SSH."
    read -rp "MQTT username [${AGENT_ID}]: " MQTT_USER
    MQTT_USER="${MQTT_USER:-$AGENT_ID}"
    read -rsp "MQTT password: " MQTT_PASS
    echo ""

    echo ""
    # Gateway
    read -rp "Local OpenClaw gateway URL [http://127.0.0.1:18789]: " GATEWAY_URL
    GATEWAY_URL="${GATEWAY_URL:-http://127.0.0.1:18789}"
    read -rp "Gateway wake mode (api or webhook) [api]: " WAKE_MODE
    WAKE_MODE="${WAKE_MODE:-api}"
    read -rsp "Gateway token (GATEWAY_TOKEN or HOOKS_TOKEN): " GATEWAY_TOKEN
    echo ""

    echo ""
    read -rp "Heartbeat interval in seconds [30]: " HEARTBEAT_SEC
    HEARTBEAT_SEC="${HEARTBEAT_SEC:-30}"

    # Save config
    cat > "$CONFIG_FILE" <<ENVEOF
# EdgeCitadel Agent Configuration
# Generated by join.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

AGENT_ID="${AGENT_ID}"
AGENT_DISPLAY="${AGENT_DISPLAY}"
AGENT_ROLE="${AGENT_ROLE}"
AGENT_DEVICE_TYPE="${AGENT_DEVICE_TYPE}"

# EdgeCitadel MQTT broker
CITADEL_HOST="${CITADEL_HOST}"
CITADEL_PORT="${CITADEL_PORT}"
MQTT_USER="${MQTT_USER}"
MQTT_PASS="${MQTT_PASS}"

# Local OpenClaw gateway
GATEWAY_URL="${GATEWAY_URL}"
WAKE_MODE="${WAKE_MODE}"
GATEWAY_TOKEN="${GATEWAY_TOKEN}"

HEARTBEAT_SEC="${HEARTBEAT_SEC}"
ENVEOF
    chmod 600 "$CONFIG_FILE"
    ok "Config saved to $CONFIG_FILE"
fi

# ── Validate required fields ──
for var in AGENT_ID CITADEL_HOST MQTT_PASS; do
    if [[ -z "${!var}" ]]; then
        err "Required config missing: $var"
        exit 1
    fi
done
CITADEL_PORT="${CITADEL_PORT:-1883}"
MQTT_USER="${MQTT_USER:-$AGENT_ID}"
AGENT_DISPLAY="${AGENT_DISPLAY:-$(echo "$AGENT_ID" | sed 's/-/ /g; s/\b\w/\u&/g')}"
AGENT_ROLE="${AGENT_ROLE:-Agent}"
AGENT_DEVICE_TYPE="${AGENT_DEVICE_TYPE:-server}"
GATEWAY_URL="${GATEWAY_URL:-http://127.0.0.1:18789}"
WAKE_MODE="${WAKE_MODE:-api}"
GATEWAY_TOKEN="${GATEWAY_TOKEN:-}"
HEARTBEAT_SEC="${HEARTBEAT_SEC:-30}"

echo ""
info "Agent:    $AGENT_ID ($AGENT_DISPLAY)"
info "Broker:   $CITADEL_HOST:$CITADEL_PORT"
info "Gateway:  $GATEWAY_URL (wake: $WAKE_MODE)"
echo ""

# ═══════════════════════════════════════════════════════════════════
# Step 2: Check prerequisites
# ═══════════════════════════════════════════════════════════════════

info "Checking prerequisites..."

if ! command -v node &>/dev/null; then
    err "Node.js not found. Install Node.js >= 16 first."
    exit 1
fi
ok "Node.js $(node -v)"

# Check mqtt module
if ! node -e "require('mqtt')" 2>/dev/null; then
    warn "npm 'mqtt' module not found. Installing..."
    cd "$SCRIPT_DIR"
    npm install mqtt 2>/dev/null || npm init -y &>/dev/null && npm install mqtt
    ok "mqtt module installed"
fi

# ═══════════════════════════════════════════════════════════════════
# Step 3: Test MQTT connectivity
# ═══════════════════════════════════════════════════════════════════

info "Testing MQTT connection to $CITADEL_HOST:$CITADEL_PORT..."

MQTT_TEST=$(node -e "
const mqtt = require('mqtt');
const client = mqtt.connect('mqtt://${CITADEL_HOST}:${CITADEL_PORT}', {
    username: '${MQTT_USER}',
    password: '${MQTT_PASS}',
    clientId: '${AGENT_ID}-test-' + Date.now(),
    connectTimeout: 10000
});
const timeout = setTimeout(() => { console.log('TIMEOUT'); process.exit(1); }, 12000);
client.on('connect', () => { clearTimeout(timeout); console.log('OK'); client.end(); });
client.on('error', (e) => { clearTimeout(timeout); console.log('ERROR:' + e.message); client.end(); process.exit(1); });
" 2>&1)

if [[ "$MQTT_TEST" == "OK" ]]; then
    ok "MQTT connection successful"
else
    err "MQTT connection failed: $MQTT_TEST"
    echo ""
    echo "  Possible causes:"
    echo "    - Wrong host/port (is EdgeCitadel running?)"
    echo "    - Wrong MQTT credentials (ask the EdgeCitadel admin to create your user)"
    echo "    - Firewall blocking port $CITADEL_PORT"
    echo ""
    echo "  To create MQTT credentials on the EdgeCitadel server, run:"
    echo "    docker compose exec mqtt mosquitto_passwd /mosquitto/config/passwd $MQTT_USER"
    echo "    docker compose restart mqtt"
    exit 1
fi

# ═══════════════════════════════════════════════════════════════════
# Step 4: Install the MQTT listener script
# ═══════════════════════════════════════════════════════════════════

info "Installing MQTT listener..."

cat > "$LISTENER_SCRIPT" <<'JSEOF'
#!/usr/bin/env node
/**
 * EdgeCitadel MQTT Listener
 *
 * Persistent connection to the EdgeCitadel MQTT broker.
 * - Publishes heartbeats (agents/heartbeat/{id}) + registration (agents/register/{id})
 * - Subscribes to agents/inbox/{id} and agents/broadcast for incoming commands
 * - Wakes the local OpenClaw gateway to process commands
 * - Forwards gateway responses back via MQTT
 */

const mqtt = require('mqtt');
const http = require('http');
const https = require('https');
const os = require('os');

// --- Config from environment ---
const AGENT_ID        = process.env.AGENT_ID;
if (!AGENT_ID) { console.error('[mqtt] AGENT_ID is required'); process.exit(1); }

const AGENT_DISPLAY   = process.env.AGENT_DISPLAY   || AGENT_ID.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
const AGENT_ROLE      = process.env.AGENT_ROLE       || 'Agent';
const AGENT_DEVICE    = process.env.AGENT_DEVICE_TYPE || 'server';
const MQTT_HOST       = process.env.CITADEL_HOST     || process.env.MQTT_HOST || '127.0.0.1';
const MQTT_PORT       = parseInt(process.env.CITADEL_PORT || process.env.MQTT_PORT || '1883');
const MQTT_USER       = process.env.MQTT_USER        || AGENT_ID;
const MQTT_PASS       = process.env.MQTT_PASS        || '';
const GATEWAY_URL     = process.env.GATEWAY_URL      || 'http://127.0.0.1:18789';
const GATEWAY_TOKEN   = process.env.GATEWAY_TOKEN    || process.env.HOOKS_TOKEN || '';
const WAKE_MODE       = process.env.WAKE_MODE        || 'api';
const HEARTBEAT_SEC   = parseInt(process.env.HEARTBEAT_SEC || '30');

const TAG = `[${AGENT_ID}-mqtt]`;

// --- MQTT Client ---
const client = mqtt.connect(`mqtt://${MQTT_HOST}:${MQTT_PORT}`, {
    username: MQTT_USER,
    password: MQTT_PASS,
    clientId: `${AGENT_ID}-listener-${Date.now()}`,
    reconnectPeriod: 5000,
    will: {
        topic: `agents/status/${AGENT_ID}`,
        payload: JSON.stringify({ status: 'offline', timestamp: new Date().toISOString() }),
        qos: 1, retain: true
    }
});

let heartbeatTimer = null;

// --- Heartbeat ---
function publishHeartbeat() {
    try {
        const loadAvg = os.loadavg()[0];
        const cpus = os.cpus().length || 1;
        const totalMem = os.totalmem();
        const freeMem = os.freemem();
        client.publish(`agents/heartbeat/${AGENT_ID}`, JSON.stringify({
            agent_id:       AGENT_ID,
            display_name:   AGENT_DISPLAY,
            role:           AGENT_ROLE,
            device_type:    AGENT_DEVICE,
            status:         'online',
            cpu_percent:    Math.round((loadAvg / cpus) * 100 * 10) / 10,
            memory_percent: Math.round(((totalMem - freeMem) / totalMem) * 100 * 10) / 10,
            ip_address:     getLocalIP(),
            capabilities:   ['chat', 'task_execution'],
            timestamp:      new Date().toISOString()
        }), { qos: 1 });
    } catch (e) {
        console.error(TAG, 'Heartbeat error:', e.message);
    }
}

// --- Registration (richer than heartbeat, sent once on connect) ---
function publishRegistration() {
    client.publish(`agents/register/${AGENT_ID}`, JSON.stringify({
        agent_id:     AGENT_ID,
        display_name: AGENT_DISPLAY,
        role:         AGENT_ROLE,
        device_type:  AGENT_DEVICE,
        capabilities: ['chat', 'task_execution', 'mqtt_listener'],
        ip_address:   getLocalIP(),
        status:       'online',
        timestamp:    new Date().toISOString()
    }), { qos: 1 });
}

function getLocalIP() {
    const ifaces = os.networkInterfaces();
    for (const name of Object.keys(ifaces)) {
        for (const iface of ifaces[name]) {
            if (iface.family === 'IPv4' && !iface.internal) return iface.address;
        }
    }
    return '127.0.0.1';
}

// --- Connect ---
client.on('connect', () => {
    console.log(TAG, `Connected to ${MQTT_HOST}:${MQTT_PORT}`);

    // Subscribe to this agent's inbox + broadcast
    client.subscribe(`agents/inbox/${AGENT_ID}`, { qos: 1 });
    client.subscribe('agents/broadcast', { qos: 1 });

    // Publish registration + initial heartbeat
    publishRegistration();
    publishHeartbeat();

    // Periodic heartbeat
    if (heartbeatTimer) clearInterval(heartbeatTimer);
    heartbeatTimer = setInterval(publishHeartbeat, HEARTBEAT_SEC * 1000);

    console.log(TAG, `Subscribed to agents/inbox/${AGENT_ID} + agents/broadcast`);
    console.log(TAG, `Heartbeat every ${HEARTBEAT_SEC}s. Online.`);
});

// --- Incoming message handler ---
client.on('message', (topic, message) => {
    try {
        const msg = JSON.parse(message.toString());

        // Normalize field names (EdgeCitadel uses from/to, also sender_id/receiver_id)
        const from    = msg.from    || msg.sender_id   || 'unknown';
        const type    = msg.type    || msg.message_type || 'unknown';
        const content = msg.content || msg.message      || '';
        const corrId  = msg.correlationId || msg.correlation_id || '';

        // Skip own messages, acks, empty
        if (from === AGENT_ID) return;
        if (type === 'ack') return;
        if (!content.trim()) return;

        console.log(TAG, `From ${from} (${type}): ${content.substring(0, 120)}`);

        // Wake the local OpenClaw gateway
        wakeGateway(from, content, corrId);
    } catch (e) {
        console.error(TAG, 'Parse error:', e.message);
    }
});

// --- Wake gateway and send reply ---
function wakeGateway(from, content, correlationId) {
    if (WAKE_MODE === 'webhook') {
        wakeViaWebhook(from, content, correlationId);
    } else {
        wakeViaAPI(from, content, correlationId);
    }
}

function wakeViaAPI(from, content, correlationId) {
    const prompt = `[MQTT from ${from}] ${content}`;
    const payload = JSON.stringify({
        messages: [{ role: 'user', content: prompt }],
        stream: false
    });

    const url = new URL(`${GATEWAY_URL}/v1/chat/completions`);
    const isHTTPS = url.protocol === 'https:';
    const headers = {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload)
    };
    if (GATEWAY_TOKEN) headers['Authorization'] = `Bearer ${GATEWAY_TOKEN}`;

    const req = (isHTTPS ? https : http).request({
        hostname: url.hostname,
        port: url.port || (isHTTPS ? 443 : 80),
        path: url.pathname,
        method: 'POST',
        headers,
        timeout: 600000
    }, (res) => {
        let data = '';
        res.on('data', (chunk) => data += chunk);
        res.on('end', () => {
            console.log(TAG, `Gateway API ${res.statusCode}`);
            try {
                const result = JSON.parse(data);
                const responseContent = result.choices?.[0]?.message?.content;
                if (responseContent?.trim()) {
                    sendReply(from, responseContent, correlationId);
                }
            } catch (e) {
                // Agent may have replied via other means
            }
        });
    });

    req.on('error', (e) => console.error(TAG, 'Gateway API error:', e.message));
    req.on('timeout', () => { req.destroy(); console.error(TAG, 'Gateway API timeout'); });
    req.write(payload);
    req.end();
}

function wakeViaWebhook(from, content, correlationId) {
    const wakeText = `[MQTT] Message from ${from}: ${content.substring(0, 500)}`;
    const postData = JSON.stringify({ text: wakeText, mode: 'now' });

    const url = new URL(`${GATEWAY_URL}/hooks/wake`);
    const headers = {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(postData)
    };
    if (GATEWAY_TOKEN) headers['Authorization'] = `Bearer ${GATEWAY_TOKEN}`;

    const req = http.request({
        hostname: url.hostname,
        port: url.port,
        path: url.pathname,
        method: 'POST',
        headers,
        timeout: 10000
    }, (res) => {
        let body = '';
        res.on('data', d => body += d);
        res.on('end', () => console.log(TAG, `Wake ${res.statusCode}: ${body.substring(0, 100)}`));
    });

    req.on('error', (e) => console.error(TAG, 'Wake failed:', e.message));
    req.write(postData);
    req.end();
}

// --- Send reply back via MQTT ---
function sendReply(to, content, correlationId) {
    const reply = {
        from:          AGENT_ID,
        to:            to,
        sender_id:     AGENT_ID,
        receiver_id:   to,
        type:          'response',
        message_type:  'result',
        content:       content,
        message:       content,
        correlationId: correlationId || '',
        correlation_id: correlationId || '',
        timestamp:     new Date().toISOString()
    };

    // Send to the sender's inbox
    client.publish(`agents/inbox/${to}`, JSON.stringify(reply), { qos: 1 });
    // Mirror for other subscribers
    client.publish('agents/mirror', JSON.stringify(reply), { qos: 1 });

    console.log(TAG, `Replied to ${to}: ${content.substring(0, 80)}`);
}

// --- Error handling ---
client.on('error', (err) => console.error(TAG, 'MQTT error:', err.message));
client.on('offline', () => {
    if (heartbeatTimer) { clearInterval(heartbeatTimer); heartbeatTimer = null; }
    console.log(TAG, 'Offline, reconnecting...');
});

// --- Graceful shutdown ---
function shutdown() {
    console.log(TAG, 'Shutting down...');
    if (heartbeatTimer) clearInterval(heartbeatTimer);
    client.publish(`agents/status/${AGENT_ID}`, JSON.stringify({
        status: 'offline', timestamp: new Date().toISOString()
    }), { qos: 1, retain: true }, () => {
        client.end();
        process.exit(0);
    });
    // Force exit after 2s if publish hangs
    setTimeout(() => process.exit(0), 2000);
}
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);

console.log(TAG, 'EdgeCitadel MQTT Listener starting...');
console.log(TAG, `Agent: ${AGENT_DISPLAY} (${AGENT_ROLE}) | Broker: ${MQTT_HOST}:${MQTT_PORT} | Gateway: ${GATEWAY_URL} (${WAKE_MODE})`);
JSEOF

chmod +x "$LISTENER_SCRIPT"
ok "Listener script installed at $LISTENER_SCRIPT"

# ═══════════════════════════════════════════════════════════════════
# Step 5: Install systemd user service
# ═══════════════════════════════════════════════════════════════════

info "Setting up systemd service..."

SERVICE_DIR="$HOME/.config/systemd/user"
SERVICE_NAME="edgecitadel-${AGENT_ID}.service"
mkdir -p "$SERVICE_DIR"

cat > "$SERVICE_DIR/$SERVICE_NAME" <<SVCEOF
[Unit]
Description=EdgeCitadel MQTT Listener for ${AGENT_ID}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$(which node) ${LISTENER_SCRIPT}
Restart=always
RestartSec=5
EnvironmentFile=${CONFIG_FILE}

[Install]
WantedBy=default.target
SVCEOF

systemctl --user daemon-reload
systemctl --user enable "$SERVICE_NAME"
systemctl --user start "$SERVICE_NAME"

ok "Service $SERVICE_NAME started and enabled"

# ═══════════════════════════════════════════════════════════════════
# Step 6: Verify
# ═══════════════════════════════════════════════════════════════════

sleep 3
info "Verifying..."

if systemctl --user is-active --quiet "$SERVICE_NAME"; then
    ok "Service is running"
else
    err "Service failed to start. Check: journalctl --user -u $SERVICE_NAME"
    exit 1
fi

# Check recent logs
echo ""
info "Recent logs:"
journalctl --user -u "$SERVICE_NAME" --no-pager -n 10 2>/dev/null || true

echo ""
echo "═══════════════════════════════════════════════════════════"
echo -e "${GREEN}  Agent '${AGENT_ID}' joined EdgeCitadel successfully!${NC}"
echo ""
echo "  The agent is now:"
echo "    - Publishing heartbeats to the EdgeCitadel MQTT broker"
echo "    - Listening for commands on agents/inbox/${AGENT_ID}"
echo "    - Visible on the EdgeCitadel dashboard"
echo ""
echo "  Useful commands:"
echo "    journalctl --user -u $SERVICE_NAME -f     # follow logs"
echo "    systemctl --user restart $SERVICE_NAME     # restart"
echo "    systemctl --user stop $SERVICE_NAME        # stop"
echo "    systemctl --user disable $SERVICE_NAME     # remove from autostart"
echo "═══════════════════════════════════════════════════════════"
